export const INFO_HEIGHT = 268;
export const INFO_ANIMATION_DURATION = 800;
export const TITLE_ANIMATION_DURATION = 600;
export const TEXT_ANIMATION_DURATION = 400;
export const LIKE_DELAY =
  INFO_ANIMATION_DURATION + TITLE_ANIMATION_DURATION * 0.5;
export const PROFILE_DELAY = LIKE_DELAY + TEXT_ANIMATION_DURATION * 0.6;
